//! `--machines`: print the §11.1.3 machine table zvm holds, and stop.
//!
//! [`crate::interpreter::MACHINES`] is what every front-end presents a story as
//! (SQ-0872), and until now the only way to read it was to open the source. A
//! machine is a *bundle* — the byte in `$1E`, the page and ink in `$2C`/`$2D`,
//! the palette those colour numbers resolve through, three §8.3 screen rules and
//! the period look — and a bundle whose members disagree is exactly the defect
//! that quest was filed for. Printing all of it side by side is what makes that
//! checkable without a debugger and without a game.
//!
//! # One table, two binaries
//!
//! This lives in `zvm` rather than in a front-end because both front-ends ask
//! the same question: `zvm-cli --machines` and `lanthorn --machines` print this
//! string and nothing else (SQ-0960). A reporter kept in one CLI is a reporter
//! the other has to copy, and the copy is what goes stale — the same argument
//! `MACHINES` itself is here for. Nothing below needs a dependency `zvm` may not
//! take: it is `format!` over the table.
//!
//! # Generated, never transcribed
//!
//! Every row, every column and every decline below comes from the table itself:
//! a second copy kept by hand goes stale and then lies. Adding a machine to
//! [`crate::interpreter`] reaches this output with no edit here, and REMOVING a
//! field would fail to compile rather than quietly stop being printed.
//!
//! **Adding one used to slip through, and no longer does.** `period_look` was
//! added to the profile and this output kept printing without it, past a test
//! whose stated job was to catch exactly that — it checked a few distinctive
//! values by hand, so a new member was invisible to it.
//! `every_member_of_the_profile_reaches_the_output` now destructures the struct
//! exhaustively, with no `..`, so the next field fails to COMPILE here until
//! someone decides what column it gets.
//!
//! # Why the colours are shown resolved
//!
//! `palette: Amiga` names a choice without stating it, and the choice is the
//! whole reason the field exists — ZMSD §8.3.1.1 lets an interpreter substitute
//! its own table, so the same colour NUMBER is a different colour on two
//! machines. **Colour 12 is the case that proves it here**, because it is the
//! Amiga's own page: §8.3.1 makes it `#5A5A5A` and Infocom's `colortable[]`
//! makes it `#424242`, so the Amiga's row would be showing a grey no Amiga ever
//! painted if this were resolved through the standard table. Six of the eleven
//! numbers differ between the two palettes (4, 5, 6, 10, 11, 12) and five agree
//! — 9 is `#FFFFFF` on both, which is why the ink column looks the same across
//! the table and the page column does not.
//!
//! # Why there is a third block, about Versions
//!
//! **A machine is not a screen.** Ask [`crate::interpreter::period_look_for`] or
//! [`crate::interpreter::palette_for`] for the IBM PC and the answer depends on
//! the story's VERSION, because Infocom shipped two IBM interpreters and they
//! disagree about white — XZIP sends it to EGA attribute 7 (`#AAAAAA`) and YZIP
//! to attribute 15 (`#FFFFFF`). Printing one row per machine, as the first two
//! blocks do, states the v1–v5 answer as though it were the only one, and a
//! reader asking "what will this story look like here" gets a colour the story
//! will never be shown. The third block is exactly the rows where the two
//! answers differ, generated by asking both (SQ-0960).
//!
//! # What is deliberately absent
//!
//! The Version 6 standard window. It is not a machine constant: an archive
//! states the picture space it was drawn for — the standard Macintosh's
//! monochrome plate asks for 480x300 where its colour plate asks for 320x200,
//! one machine and two spaces — so it belongs to the file rather than to the
//! table, and it lives in `app::interpreter` where a file can be read.

use crate::interpreter::{
    palette_for, period_look_for, CursorShape, MachineProfile, PeriodLook, StatusBand, MACHINES,
};
use crate::screen::{rgb15_to_888, true_colour_in, Palette};

/// `#RRGGBB` for a true colour that has already been settled — a period look
/// arrives as RGB, whether the row measured it or its palette resolved it.
fn hex((r, g, b): (u8, u8, u8)) -> String {
    format!("#{r:02X}{g:02X}{b:02X}")
}

/// How the machine set its status line apart, in a column's width.
fn status(band: StatusBand) -> String {
    match band {
        StatusBand::FullReverse => "reversed".to_string(),
        StatusBand::PerRun => "reversed per run".to_string(),
        StatusBand::Own { ground, ink } => format!("{} on {}", hex(ink), hex(ground)),
        StatusBand::Ruled => "ruled, same ground".to_string(),
    }
}

/// The cursor, as shape and colour — neither derivable from the other, and on
/// one machine (the Amiga) the colour is neither the page nor the ink.
///
/// `ReverseSpace` prints no colour because it has none to print: it is the pair on
/// screen, reversed. No stored row carries it — `zvm::interpreter::period_look_for`
/// substitutes it for a Version 6 story, and this table is the machines rather than
/// any one story (SQ-0947).
fn cursor(look: &PeriodLook) -> String {
    let shape = match look.cursor_shape {
        CursorShape::Bar => "bar",
        CursorShape::Block => "block",
        CursorShape::Underscore => "underscore",
        CursorShape::ReverseSpace => return "reversed cell".to_string(),
    };
    format!("{shape} {}", hex(look.cursor_colour))
}

/// The period-look table, which is a second block rather than four more columns
/// because it is a different KIND of claim — see the module docs.
///
/// **Asked of [`period_look_for`], not read off the rows** (SQ-0983). Most rows
/// store their look and the two are the same string either way; the IBM PC's does
/// not store a pair at all, because its screen is its own palette resolving the
/// pair block 1 already prints. This block is the v1–v5 answer, which is the
/// Version the block is about — block 3 is where a machine whose answer moves says
/// so. Reading the rows instead is what let that machine print a page nothing was
/// ever painted in.
fn period_looks() -> String {
    let name_w = MACHINES.iter().map(|m| m.name.len()).max().unwrap_or(0);
    let mut s = format!("\n{LOOK_INTRO}\n");
    s.push_str(&format!(
        "  {:>2}  {:<name_w$}  {:<7}  {:<7}  {:<18}  {}\n",
        "#", "machine", "page", "ink", "status line", "cursor"
    ));
    s.push_str(&format!("  {}\n", "-".repeat(name_w + 48)));
    for m in MACHINES {
        let (page, ink, band, cur) = match period_look_for(m.number, None) {
            Some(l) => (hex(l.page), hex(l.ink), status(l.status), cursor(&l)),
            None => ("-".into(), "-".into(), "-".into(), "no capture".into()),
        };
        s.push_str(&format!(
            "  {:>2}  {:<name_w$}  {page:<7}  {ink:<7}  {band:<18}  {cur}\n",
            m.number, m.name,
        ));
    }
    s
}

/// The graphics mode a palette IS, named finely enough to tell two generations
/// of one machine apart.
///
/// Block 1's palette column says only "EGA" for all three IBM entries, and its
/// own comment argues why: a row that states no Version cannot honestly claim
/// XZIP over YZIP. Block 3 states the Version in the row beside this, so here it
/// can — and must, since the whole point of that block is that the two are
/// different screens.
fn mode(p: Palette) -> &'static str {
    match p {
        Palette::Standard => "ZMSD 8.3.1",
        Palette::Amiga => "Amiga",
        Palette::IbmXzip => "EGA (XZIP)",
        Palette::IbmYzip => "EGA (YZIP)",
        // Reachable through `mode`, never through a row: no machine's Version
        // selects the card. It is in the trailer below instead (SQ-0956).
        Palette::IbmCga => "CGA card",
    }
}

/// The third block: the machines whose screen the story's VERSION moves.
///
/// **Generated by asking, not by listing.** Every row here is
/// [`period_look_for`] and [`palette_for`] answered twice — once for a v1–v5
/// story, once for a Version 6 one — and printed only where the two answers
/// differ. A machine that gains a version-dependent anything appears here with
/// no edit, and the two that have one today (the IBM PC's palette and ink, the
/// Amiga's and the IBM PC's caret) cannot quietly stop appearing.
///
/// The `5` and the `6` are the only two questions worth asking: both functions
/// branch on `Some(6)` and on nothing else, so every version below 6 gives one
/// answer and 6 gives the other.
fn version_moves() -> String {
    let name_w = MACHINES.iter().map(|m| m.name.len()).max().unwrap_or(0);
    let ask = |number: u8, v: u8| (palette_for(number, Some(v)), period_look_for(number, Some(v)));
    let mut rows = String::new();
    for m in MACHINES {
        let (early, late) = (ask(m.number, 5), ask(m.number, 6));
        if early == late {
            continue;
        }
        for (label, (palette, look)) in [("v1-v5", early), ("v6", late)] {
            let (page, ink, cur) = match &look {
                Some(l) => (hex(l.page), hex(l.ink), cursor(l)),
                None => ("-".into(), "-".into(), "no capture".into()),
            };
            rows.push_str(&format!(
                "  {:>2}  {:<name_w$}  {label:<6}  {:<11}  {page:<7}  {ink:<7}  {cur}\n",
                m.number,
                m.name,
                mode(palette),
            ));
        }
    }
    let mut s = format!("\n{MOVES_INTRO}\n");
    s.push_str(&format!(
        "  {:>2}  {:<name_w$}  {:<6}  {:<11}  {:<7}  {:<7}  {}\n",
        "#", "machine", "story", "graphics", "page", "ink", "cursor"
    ));
    s.push_str(&format!("  {}\n", "-".repeat(name_w + 51)));
    if rows.is_empty() {
        // Not reachable today, and printed rather than skipped if it ever is: an
        // empty block says "asked and nothing moved", where no block at all is
        // indistinguishable from having forgotten to ask.
        s.push_str("  (no machine's answer moves with the story's Version)\n");
    } else {
        s.push_str(&rows);
    }
    s.push_str(&format!("\n{MOVES_LEGEND}"));
    s
}

/// `#RRGGBB` for standard colour number `n` **through `palette`**, or a dash
/// when the number has no true-colour equivalent (§8.3.7's sentinels).
///
/// Asked by VALUE, through [`crate::screen::true_colour_in`]. It used to borrow
/// the process-wide palette per row and hand it straight back, arguing that
/// nothing else was running because `--machines` prints and exits before a story
/// is read — true of a binary, false of a test harness, and false again the
/// moment this module moved into `zvm` beside cases that set the palette
/// themselves. A pure lookup cannot race with any of them (SQ-0904's lesson,
/// applied where it costs nothing).
fn swatch(n: u8, palette: Palette) -> String {
    true_colour_in(palette, n)
        .map(rgb15_to_888)
        .map(|(r, g, b)| format!("#{r:02X}{g:02X}{b:02X}"))
        .unwrap_or_else(|| "-".to_string())
}

/// One machine's page and ink, as `bg=N #RRGGBB fg=N #RRGGBB` — or why it has
/// none. A `None` here is a DECLINE with two different meanings, and the table
/// says which by naming the machine rather than by inventing a pair.
fn colours(m: &MachineProfile) -> String {
    match m.default_colours {
        Some((bg, fg)) => {
            format!("bg {bg:>2} {}   fg {fg:>2} {}", swatch(bg, m.palette), swatch(fg, m.palette))
        }
        None => "the player's own terminal".to_string(),
    }
}

/// The whole table, ready to print.
pub fn table() -> String {
    let mut s = format!("ZMSD §11.1.3 machine profiles — what zvm models, in number order.\n\n{TOLD_INTRO}\n");
    let name_w = MACHINES.iter().map(|m| m.name.len()).max().unwrap_or(0);
    s.push_str(&format!(
        "  {:>2}  {:<name_w$}  {:<32}  {:<8}  {:<11}  {:<14}  {:<18}  {:<8}  {:<10}  {:<9}  {:<14}  {:<14}  {}\n",
        "#", "machine", "default page / ink ($2C/$2D)", "palette", "global pens", "v6 screen page",
        "one screen palette", "v6 cell", "face space", "emphasis", "system face", "v6 std window",
        "v6 wrap"
    ));
    s.push_str(&format!("  {}\n", "-".repeat(name_w + 173)));
    for m in MACHINES {
        s.push_str(&format!(
            "  {:>2}  {:<name_w$}  {:<32}  {:<8}  {:<11}  {:<14}  {:<18}  {:<8}  {:<10}  {:<9}  {:<14}  {:<14}  {}\n",
            m.number,
            m.name,
            colours(m),
            match m.palette {
                Palette::Standard => "standard",
                Palette::Amiga => "Amiga",
                // SQ-0939: the IBM PC resolves through EGA, and its white moves
                // with the interpreter generation. The row shows the machine's
                // BASE palette; `zvm::interpreter::palette_for` is what picks the
                // v6 one at boot, so naming XZIP here would overstate what a row
                // can say on its own.
                // SQ-0956: `IbmCga` is a CARD rather than a machine, so no row
                // states it — it is installed at boot from the ARCHIVE a launch
                // loaded, which this table has no column for and cannot.
                Palette::IbmXzip | Palette::IbmYzip | Palette::IbmCga => "EGA",
            },
            yes_no(m.global_colour_pens),
            yes_no(m.v6_screen_page),
            yes_no(m.one_screen_palette),
            format!("{}x{}", m.v6_cell.w(), m.v6_cell.h()),
            // Which space this machine's own RELEASE typefaces are authored in,
            // which is not always the space its ARTWORK is (SQ-1039), and not always
            // the space its SYSTEM face is either (SQ-1053). Only the Amiga says
            // `art`; its own topaz is `hires`, and that is the system face's fact
            // rather than the row's.
            match m.v6_release_face_space {
                crate::interpreter::V6FaceSpace::Art => "art",
                crate::interpreter::V6FaceSpace::Native => "native px",
                crate::interpreter::V6FaceSpace::Hires => "hires",
            },
            // §8.7.1's Italic bit: a rule under the cell, or a synthesised slope
            // (SQ-1028). Only the two machines Infocom shipped a v6 interpreter for
            // have a capture to measure, and both underline.
            match m.v6_emphasis {
                crate::interpreter::V6Emphasis::Underline => "underline",
                crate::interpreter::V6Emphasis::Slope => "slope",
            },
            // What this machine's own SYSTEM body face is called on its boot media
            // (SQ-1037). Only the two machines Infocom shipped a v6 interpreter for
            // name one, because only they had a body face to go looking for: Geneva
            // is in the Macintosh System file, topaz in the Amiga's ROM and its
            // `FONTS:` drawer, and neither is on any game disk. A dash is "nothing
            // to name", not "unmeasured".
            match m.v6_system_face {
                Some(crate::interpreter::V6SystemFace::MacFamily(f)) => {
                    format!("FONT family {f}")
                }
                Some(crate::interpreter::V6SystemFace::AmigaDrawer(d)) => {
                    format!("fonts/{d}")
                }
                None => "-".to_string(),
            },
            // A machine that states none defers to the story's own container, and
            // to any artwork the host mounted ahead of it (SQ-0838).
            m.v6_std_window.map_or("the archive's".to_string(), |(w, h)| format!("{w}x{h}")),
            // How this machine decides what a v6 window does with text that reaches
            // its right margin (SQ-1071). §8.8.3.1.2.2's commentary tabulates
            // Infocom's own interpreters and the two that shipped a Version 6
            // interpreter IGNORE the window attributes, following `buffer_mode`
            // instead; the flow named is the one they use with buffering OFF, since
            // buffering ON is word wrap on both.
            match m.v6_wrap_regime {
                crate::interpreter::V6WrapRegime::Attributes => "attributes".to_string(),
                crate::interpreter::V6WrapRegime::BufferMode { unbuffered } => {
                    format!("buffer_mode/{}", match unbuffered {
                        crate::interpreter::V6TextFlow::WordWrap => "word",
                        crate::interpreter::V6TextFlow::CharWrap => "char",
                        crate::interpreter::V6TextFlow::CharClip => "clip",
                    })
                }
            },
        ));
    }
    s.push_str(&format!("\n{LEGEND}"));
    s.push_str(&period_looks());
    s.push_str(&version_moves());
    // The gaps are the other half of the table: `machine()` answering None says
    // "a machine I do not model", and a reader who cannot see which numbers
    // those are cannot tell that from an oversight.
    let modelled: Vec<u8> = MACHINES.iter().map(|m| m.number).collect();
    let absent: Vec<String> = (1u8..=11)
        .filter(|n| !modelled.contains(n))
        .map(|n| format!("{n} ({})", NUMBERED.iter().find(|(k, _)| *k == n).map_or("?", |(_, v)| v)))
        .collect();
    s.push_str(&format!("\nNot modelled: {}.\n{ABSENT}", absent.join(", ")));
    s
}

fn yes_no(b: bool) -> &'static str {
    if b { "yes" } else { "no" }
}

/// §11.1.3's own names, for the numbers the table declines — the only place a
/// name is written by hand, because a row that does not exist cannot state one.
const NUMBERED: &[(u8, &str)] = &[
    (1, "DECSystem-20"),
    (2, "Apple IIe"),
    (3, "Macintosh"),
    (4, "Amiga"),
    (5, "Atari ST"),
    (6, "IBM PC"),
    (7, "Commodore 128"),
    (8, "Commodore 64"),
    (9, "Apple IIc"),
    (10, "Apple IIgs"),
    (11, "Tandy Color"),
];

/// The blocks' headers, and why there is more than one.
///
/// **They are different kinds of claim and must not be read as one table.**
/// The first is what the STORY IS TOLD — header bytes and §8.3 rules, every value
/// read out of Infocom's own source. The second is what the SCREEN LOOKED LIKE,
/// every value observed from an emulator capture. Merging them would put a sourced
/// constant and an observation in the same row under the same authority, and would
/// also run past 160 columns; keeping them apart is what lets each say where it
/// came from. Numbering them is what stops the second looking like an accident.
///
/// The third ([`MOVES_INTRO`]) is a different kind again: not a machine's values
/// but the machines whose values a story's VERSION moves, computed from the two
/// above rather than stated. It is last because it is only legible once a reader
/// knows what it is amending.
///
/// Written as plain literals for the reason [`ABSENT`] is: a `"\` continuation eats
/// the newline AND the indent after it, so an indented continuation line silently
/// loses its leading spaces.
const TOLD_INTRO: &str = "1. WHAT THE STORY IS TOLD - the header bytes and the section 8.3 screen rules,
   each value read out of Infocom's own interpreter source.
   Colours are resolved through each machine's OWN palette (section 8.3.1.1).
";

/// See [`TOLD_INTRO`].
const LOOK_INTRO: &str = "2. WHAT THE SCREEN LOOKED LIKE - presentation for a v1-v4 story, which has no
   colour concept for the pairs above to be the default OF.
   OBSERVED from emulator captures in machine-screenshots/, not read out of
   Infocom's source as the pairs above are. A dash is a machine with no
   capture, not a machine with no look.
   Ask for it with zvm-cli's --period-look (off by default there, on in
   lanthorn); the cursor's SHAPE is drawn with DECSCUSR, its colour cannot be.
   ONE ROW IS RESOLVED RATHER THAN OBSERVED. The IBM PC's screen IS its own
   palette's rendering of the pair it reports in block 1, so its page and ink
   are that lookup and no pair is stored for them - two of Infocom's IBM
   interpreters disagree about white, so the value depends on the story's
   Version and block 3 says how. The adapter's own entries are EGA 1 #0000AA
   and EGA 7 #AAAAAA, which is the truth about the hardware; a colour number
   reaches a story through the Z-machine's 15-bit space, where 0xAA truncates
   to 21/31 and comes back bit-replicated as 0xAD. Three parts in 255, an
   artifact of the colour space rather than an error in either value, and
   #0000AD / #ADADAD is what the screen gets.
";

/// See [`TOLD_INTRO`].
const MOVES_INTRO: &str = "3. WHAT THE STORY'S VERSION CHANGES - the rows above are the v1-v5 answer, and
   on some machines a Version 6 story reached a different interpreter with a
   different screen. Only the machines where the two answers DIFFER are listed;
   every other machine answers block 2 for any story.
   Generated by asking period_look_for/palette_for both ways, so a machine that
   gains a version-dependent value appears here on its own.
";

/// See [`LEGEND`].
const MOVES_LEGEND: &str = "\
story       the story file's Z-machine Version, not the interpreter's own.
graphics    the palette section 8.3.1 colour NUMBERS resolve through, which for
            the IBM PC is which of Infocom's two interpreters a story would
            have run under: XZIP (v1-v5) sends white to EGA attribute 7,
            #AAAAAA, and YZIP (v6) to attribute 15, #FFFFFF. One entry apart,
            and it is the one every page and ink here is drawn in.
cursor      'reversed cell' is the pair on screen, reversed - a caret with no
            colour of its own, which is what Version 6 moved these two to.
page / ink  RESOLVED through the mode beside them. Block 2 prints the same
            values for the v1-v5 row, because both blocks ask period_look_for,
            which is the question a front-end asks; what this block adds is
            what Version 6 moves. Block 2's note says why the IBM PC's page
            reads #0000AD where the adapter's own entry is #0000AA.

A third IBM graphics mode reaches no row here, because no Version selects it:
the CGA card, installed from the picture ARCHIVE a launch loads (lanthorn's
--pictures foo.cg1). It is a two-state display, so a story's pair carries one
bit rather than two colours, and colour 9 is the card's #AAAAAA whichever
Version asks.
";

const LEGEND: &str = "\
global pens     §8.3's Amiga rule: one pair of text pens for the whole screen,
                so a set_colour moves the screen rather than one window.
v6 screen page  the machine's default pair IS the Version 6 screen — the ground
                every window that names no colour of its own is read on.
one screen      the whole screen shows through ONE palette, so a picture's own
palette         colours repaint everything already drawn, border art included.
";

// NOT a `"\` continuation: that escape eats the newline AND the leading
// whitespace after it, so the first row would lose the indent every other row
// keeps and the block would come out ragged.
const ABSENT: &str = "  1   what declining a number already falls through to; whether it deserves a
      bundle or is honestly \"a terminal, the same as the IBM PC\" is a decision.
  11  no fixture and no sourced constant; anything here would be guesswork.
";

// **No test here takes a palette lock, and there is no longer one to take.** The
// module used to keep a `PALETTE` mutex because [`swatch`] borrowed a process-wide
// palette per row and handed it straight back — safe in a binary that prints and
// exits, a race in a test harness where one process runs many cases on many threads
// (SQ-0904, and CI runs `cargo test`). `swatch` asks `screen::true_colour_in` by
// value and touches no shared state at all, and since SQ-1393 the palette is a
// `Machine` field, so there is nothing left in the crate that could reintroduce
// the window.

#[cfg(test)]
mod tests {
    use super::*;
    use crate::interpreter::MachineLook;

    /// Every modelled machine appears, with its number and its name.
    #[test]
    fn the_table_lists_every_machine_zvm_models() {
        let t = table();
        for m in MACHINES {
            assert!(t.contains(m.name), "{} is missing from the table", m.name);
            assert!(
                t.lines().any(|l| l.trim_start().starts_with(&format!("{}  ", m.number))
                    && l.contains(m.name)),
                "{} ({}) has no row of its own:\n{t}",
                m.name,
                m.number
            );
        }
    }

    /// **Every field of the profile is printed**, and the check is mechanical.
    ///
    /// The struct is the contract, and a member added to it and not to this output
    /// is the failure this catches. It did not catch `period_look`: the test used to
    /// name a few machines that answer distinctively and assert on those, which says
    /// nothing at all about a member nobody thought to add an assertion for.
    ///
    /// The exhaustive `let` destructure below — no `..` — is what makes it real. Add
    /// a field to `MachineProfile` and this stops COMPILING until someone decides
    /// which column it belongs in. The per-value assertions that follow are then
    /// worth something, because the binding list is guaranteed complete.
    #[test]
    fn every_member_of_the_profile_reaches_the_output() {
        let t = table();
        let row = |name: &str| {
            t.lines().find(|l| l.contains(name)).unwrap_or_else(|| panic!("no {name} row")).to_string()
        };

        for m in MACHINES {
            // Exhaustive on purpose. Adding a member breaks the build here.
            let MachineProfile {
                number,
                name,
                default_colours,
                palette,
                global_colour_pens,
                v6_screen_page,
                one_screen_palette,
                v6_cell,
                v6_release_face_space,
                v6_system_face,
                v6_emphasis,
                v6_std_window,
                period_look,
                v6_wrap_regime,
            } = *m;
            let rows: Vec<&str> = t.lines().filter(|l| l.contains(name)).collect();
            assert!(!rows.is_empty(), "{name} has no row");
            let all = rows.join("\n");
            assert!(all.contains(&number.to_string()), "{name}: number");
            match default_colours {
                Some((bg, fg)) => assert!(
                    all.contains(&format!("bg {bg:>2}")) && all.contains(&format!("fg {fg:>2}")),
                    "{name}: default_colours {bg}/{fg} not in\n{all}",
                ),
                None => assert!(all.contains("the player's own terminal"), "{name}: a decline says so"),
            }
            let palette_name = match palette {
                Palette::Standard => "standard",
                Palette::Amiga => "Amiga",
                // No MachineProfile states `IbmCga` — it is a card, installed
                // from the archive rather than from a row (SQ-0956).
                Palette::IbmXzip | Palette::IbmYzip | Palette::IbmCga => "EGA",
            };
            assert!(all.contains(palette_name), "{name}: palette");
            assert!(
                all.contains(match v6_release_face_space {
                    crate::interpreter::V6FaceSpace::Art => "art",
                    crate::interpreter::V6FaceSpace::Native => "native px",
                    crate::interpreter::V6FaceSpace::Hires => "hires",
                }),
                "{name}: v6_release_face_space not in\n{all}",
            );
            assert!(
                all.contains(match v6_emphasis {
                    crate::interpreter::V6Emphasis::Underline => "underline",
                    crate::interpreter::V6Emphasis::Slope => "slope",
                }),
                "{name}: v6_emphasis not in\n{all}",
            );
            assert!(
                all.contains(&match v6_wrap_regime {
                    crate::interpreter::V6WrapRegime::Attributes => "attributes".to_string(),
                    crate::interpreter::V6WrapRegime::BufferMode { unbuffered } =>
                        format!("buffer_mode/{}", match unbuffered {
                            crate::interpreter::V6TextFlow::WordWrap => "word",
                            crate::interpreter::V6TextFlow::CharWrap => "char",
                            crate::interpreter::V6TextFlow::CharClip => "clip",
                        }),
                }),
                "{name}: v6_wrap_regime not in\n{all}",
            );
            assert!(
                all.contains(&match v6_system_face {
                    Some(crate::interpreter::V6SystemFace::MacFamily(f)) =>
                        format!("FONT family {f}"),
                    Some(crate::interpreter::V6SystemFace::AmigaDrawer(d)) => format!("fonts/{d}"),
                    None => "-".to_string(),
                }),
                "{name}: v6_system_face not in\n{all}",
            );
            // The three booleans share one spelling, so count rather than search:
            // the machine table row holds exactly these three yes/no columns.
            let want = usize::from(global_colour_pens)
                + usize::from(v6_screen_page)
                + usize::from(one_screen_palette);
            assert_eq!(rows[0].matches("yes").count(), want, "{name}: screen rules\n{all}");
            // SQ-1013: the two Version 6 geometry columns. The cell always prints
            // — every machine declares one — and the standard window prints either
            // its size or the reason it has none, because "blank" and "defers to
            // the archive" are different answers and a reader cannot tell them
            // apart from an empty column.
            assert!(
                all.contains(&format!("{}x{}", v6_cell.w(), v6_cell.h())),
                "{name}: v6 cell {}x{} not in\n{all}",
                v6_cell.w(),
                v6_cell.h(),
            );
            match v6_std_window {
                Some((w, h)) => {
                    assert!(all.contains(&format!("{w}x{h}")), "{name}: v6 std window\n{all}")
                }
                None => assert!(all.contains("the archive's"), "{name}: a decline says so\n{all}"),
            }
            // Exhaustive on the VARIANT too, for the same reason the destructure
            // above is exhaustive on the fields: a row that stores its look and one
            // that resolves it store different things, and a new variant must
            // decide what reaches the reader before this compiles (SQ-0983).
            match period_look {
                Some(MachineLook::Measured(l)) => {
                    assert!(all.contains(&hex(l.page)), "{name}: period page");
                    assert!(all.contains(&hex(l.ink)), "{name}: period ink");
                    assert!(all.contains(&status(l.status)), "{name}: status band");
                    assert!(all.contains(&cursor(&l)), "{name}: cursor");
                }
                Some(MachineLook::Resolved { status: band, cursor_shape }) => {
                    // The two decisions the row DOES state reach the output…
                    assert!(all.contains(&status(band)), "{name}: status band");
                    // …and the pair it does not is printed as the machine resolves
                    // it, which is the only pair that was ever on a screen.
                    let l = period_look_for(number, None).expect("a resolved row answers");
                    assert_eq!(l.cursor_shape, cursor_shape, "{name}: the stored caret shape");
                    assert!(all.contains(&hex(l.page)), "{name}: resolved page");
                    assert!(all.contains(&hex(l.ink)), "{name}: resolved ink");
                    assert!(all.contains(&cursor(&l)), "{name}: cursor");
                }
                None => assert!(all.contains("no capture"), "{name}: a period decline says so"),
            }
        }

        // …and the distinctive rows still read the way they should.
        let amiga = row("Amiga");
        assert_eq!(amiga.matches("yes").count(), 3, "global pens, v6 page AND one palette: {amiga}");
        let mac = row("Macintosh");
        assert_eq!(mac.matches("yes").count(), 1, "v6 page only: {mac}");
        let pc = row("IBM PC");
        assert_eq!(pc.matches("yes").count(), 0, "no screen rules: {pc}");
    }

    /// The period look is printed as its own block, and says it is observed rather
    /// than sourced — the distinction the whole field rests on (SQ-0873).
    #[test]
    fn the_period_look_block_states_where_it_came_from() {
        let t = table();
        assert!(t.contains("OBSERVED from emulator captures"), "provenance is stated");
        assert!(t.contains("machine-screenshots/"), "and says where to look");
        // Three cursor shapes and three status behaviours reach the reader.
        for s in ["bar #000000", "block #FF7E1C", "underscore #55FFFF"] {
            assert!(t.contains(s), "cursor {s} missing:\n{t}");
        }
        // SQ-0873: "reversed per run" no longer appears — the two machines measured
        // that way draw a full-width reverse instead, on the user's ruling. The
        // variant survives in `StatusBand` as the record of the measurement.
        for s in ["reversed", "ruled, same ground"] {
            assert!(t.contains(s), "status {s} missing");
        }
        assert!(!t.contains("reversed per run"), "no row renders a per-run band now:\n{t}");
        // SQ-0933: the Atari ST was the last row printing "no capture", and
        // `st-zork1.png` filled it — so NO row says that now, and the ST prints a
        // measured white page like every other machine. The decline branch above
        // still covers a future unmeasured row; this pins that there isn't one.
        assert!(!t.contains("no capture"), "every modelled machine is measured now:\n{t}");
        let st = t.lines().find(|l| l.contains("Atari ST")).expect("the ST has a row");
        assert!(st.contains("#FFFFFF"), "the ST's page is white: {st}");
    }

    /// The colours are resolved through the row's OWN palette, which is the
    /// claim the header makes and the only thing that makes the columns true.
    ///
    /// **Colour 12 is the case that can show it**, and picking the right number
    /// mattered: 9 is `#FFFFFF` in both palettes, so a row rendered through the
    /// wrong one would still print white and pass. Twelve is the Amiga's own
    /// page — `#5A5A5A` under §8.3.1 and `#424242` under Infocom's
    /// `colortable[]` — so it is on screen in the table AND divergent, which is
    /// what makes it evidence rather than coincidence.
    ///
    /// Falsifiable: resolve `swatch` through `Palette::Standard` for every row
    /// and the Amiga's page comes back `#5A5A5A`.
    #[test]
    fn each_row_resolves_its_colours_through_its_own_palette() {
        assert_eq!(swatch(12, Palette::Standard), "#5A5A5A", "§8.3.1's dark grey");
        assert_eq!(swatch(12, Palette::Amiga), "#424242", "the Amiga's own");
        assert_eq!(swatch(9, Palette::Standard), swatch(9, Palette::Amiga), "…and 9 agrees");
        let t = table();
        let amiga = t.lines().find(|l| l.contains("Amiga  ")).expect("the Amiga row");
        assert!(amiga.contains("bg 12 #424242"), "the Amiga's page is its own grey: {amiga}");
        assert!(!amiga.contains("#5A5A5A"), "…and never the standard table's: {amiga}");
    }

    /// **This module resolves colours without touching the process palette at
    /// all**, which is what let its test lock go away — see the comment above
    /// `mod tests`. It used to borrow the global per row and hand it back, and
    /// the case here used to check the handing back.
    ///
    /// A source-level case, because the property is an ABSENCE and an absence has
    /// no call site to assert on. Reaching for `set_palette` again would pass
    /// every other case in this file and quietly reintroduce SQ-0904's race, in a
    /// crate whose own `screen.rs` cases set the palette with no lock at all.
    #[test]
    fn printing_the_table_never_writes_the_process_palette() {
        let src = include_str!("machines.rs");
        // Spelled in two pieces so this line is not itself the match.
        assert!(
            !src.contains(concat!("set_", "palette(")),
            "a table presents as every machine at once; ask `true_colour_in` by value instead",
        );
    }

    /// The declines are printed too, and are exactly the numbers with no row.
    #[test]
    fn the_numbers_with_no_row_are_named_and_argued() {
        let t = table();
        for (n, name) in [(1u8, "DECSystem-20"), (11, "Tandy Color")] {
            assert!(t.contains(&format!("{n} ({name})")), "{name} must be listed as absent");
        }
        for m in MACHINES {
            assert!(
                !t.contains(&format!("Not modelled: {} ", m.number)),
                "{} is modelled and must not be listed absent",
                m.name
            );
        }
    }

    /// **Block 3 is exactly the machines whose answer the Version moves** — asked
    /// of the table, never listed by hand (SQ-0960).
    ///
    /// The whole point of the block is that a row per machine states the v1–v5
    /// screen as though it were the only one. So the test computes the set the
    /// same way the block does and checks the block prints that set and no other:
    /// a machine that stops moving must lose its rows, and one that starts must
    /// gain them, with no edit to either side.
    #[test]
    fn the_version_block_lists_every_machine_whose_screen_the_version_moves() {
        let moves = |n: u8| {
            (palette_for(n, Some(5)), period_look_for(n, Some(5)))
                != (palette_for(n, Some(6)), period_look_for(n, Some(6)))
        };
        let block = version_moves();
        for m in MACHINES {
            // ROWS, not mentions: the block's own legend names the IBM PC in
            // prose, and counting that would have made this case pass at three.
            let rows = block.lines().filter(|l| is_row(l, m.number, m.name)).count();
            if moves(m.number) {
                assert_eq!(rows, 2, "{} moves, so it needs a v1-v5 row AND a v6 row:\n{block}", m.name);
            } else {
                assert_eq!(rows, 0, "{} answers the same either way, so it has no row:\n{block}", m.name);
            }
        }
        // Non-vacuity: an empty block would satisfy every `== 0` above and say
        // nothing. Two machines move today, which is four rows.
        let moving: Vec<&str> =
            MACHINES.iter().filter(|m| moves(m.number)).map(|m| m.name).collect();
        assert_eq!(moving, ["Amiga", "IBM PC"], "the two machines Version 6 moved");
    }

    /// The two values that move are the ones a reader can ACT on: the graphics
    /// mode and the colour it draws.
    ///
    /// Sourced in [`crate::interpreter::palette_for`]'s own docs and corroborated
    /// there by a capture each: XZIP sends white to EGA attribute 7 and YZIP to
    /// 15, one entry apart, and every page and ink in the block is drawn through
    /// whichever it is. A block naming the machine and not the mode would be the
    /// same defect the block exists to fix.
    #[test]
    fn the_ibm_pcs_two_generations_print_their_mode_and_their_white() {
        let block = version_moves();
        let (early, late) = (row_of(&block, 6, "IBM PC", "v1-v5"), row_of(&block, 6, "IBM PC", "v6"));
        assert!(early.contains("EGA (XZIP)"), "the v1-v5 mode is named: {early}");
        assert!(late.contains("EGA (YZIP)"), "the v6 mode is named: {late}");
        // **The white is the one entry the two tables disagree on**, and it is
        // printed as the SCREEN gets it rather than as the adapter names it: EGA
        // attribute 7 is #AAAAAA, which the Z-machine's 15-bit colour space
        // truncates to 21/31 and replicates back as #ADADAD. Attribute 15 is
        // #FFFFFF, which survives the same round trip exactly — 31/31 — so the
        // move is visible in the output and not swallowed by it.
        assert!(early.contains("#ADADAD"), "…attribute 7, through 15-bit: {early}");
        assert!(late.contains("#FFFFFF"), "…against attribute 15: {late}");
        assert!(early.contains("#0000AD") && late.contains("#0000AD"), "the page does not move");
        // The caret moved on both machines, and is the pair reversed rather than a
        // colour (SQ-0947).
        assert!(late.contains("reversed cell"), "the v6 caret has no colour of its own: {late}");
        let amiga = row_of(&block, 4, "Amiga", "v1-v5");
        assert!(amiga.contains("block #FF7E1C"), "the Amiga's v1-v5 caret is its orange: {amiga}");
        assert!(
            row_of(&block, 4, "Amiga", "v6").contains("reversed cell"),
            "…and Version 6 reverses the pair instead:\n{block}"
        );
    }

    /// The CGA card is named, and named as a card rather than as a row.
    ///
    /// It is the third IBM graphics mode and no story Version selects it — it is
    /// installed from the picture ARCHIVE a launch loads (SQ-0956), which this
    /// table has no column for. A reader comparing two EGA rows would otherwise
    /// conclude EGA is all there is.
    #[test]
    fn the_cga_card_is_named_as_a_card_and_never_as_a_version() {
        let block = version_moves();
        assert!(block.contains("CGA card"), "the card is named:\n{block}");
        assert!(
            !block.lines().any(|l| l.contains("CGA card") && l.contains("IBM PC")),
            "…but never as a machine's row, because no Version reaches it:\n{block}"
        );
        assert_eq!(mode(Palette::IbmCga), "CGA card", "and it is spelled as a card");
    }

    /// A printed ROW for this machine, as against the prose that names it.
    fn is_row(line: &str, number: u8, name: &str) -> bool {
        line.trim_start().starts_with(&format!("{number}  ")) && line.contains(name)
    }

    fn row_of<'a>(block: &'a str, number: u8, name: &str, version: &str) -> &'a str {
        block
            .lines()
            .find(|l| is_row(l, number, name) && l.contains(version))
            .unwrap_or_else(|| panic!("no {name} {version} row:\n{block}"))
    }
}

