//! Synonym groups for interactive-fiction verbs — the bridge from a word the
//! player typed to one the story actually knows.
//!
//! ## What this is for
//!
//! A player types `illuminate lamp`. The story wants `light`. Nothing in the
//! story file records what `illuminate` MEANS, and every mechanism that works on
//! FORM fails on it: edit distance is 8 on a 10-letter word, stemming reaches
//! `illuminat-` and nothing else, and the grammar's shape only says "a verb
//! taking one noun", which is most verbs. The bridge has to come from outside
//! the story, so it is generated offline and shipped: [`synonym_groups.tsv`],
//! beside this file.
//!
//! ## Where the data came from, and how to regenerate it
//!
//! Two sources, and the first of them is interactive fiction itself.
//!
//! Every story's grammar declares its verbs in GROUPS — `Verb 'examine' 'x'
//! 'watch' 'describe' 'inspect'` is one entry, and it is that game's author
//! stating that those spellings are one action. Where several stories declare
//! the same set independently, it is shipped as a group. That source outranks
//! the second one, because it answers the parser's question rather than
//! English's: WordNet relates `inspect` to `case`, `visit` and `audit`, and to
//! `examine` not at all, while fourteen stories in the corpus put `inspect` and
//! `examine` on one verb.
//!
//! The second is WordNet 3.0 (Princeton University), filtered by the 12dicts
//! 6.0.2 lemmatized frequency list (Alan Beale, under the AGID terms) down to
//! the senses the IF vocabulary actually touches. It covers everything the
//! corpus never happened to group.
//!
//! `crates/verb-synonyms-gen` builds the table from both, against the verb
//! vocabulary harvested from every story its three parsers can read. See that
//! crate's `README.md` for the exact source versions and the two commands; the
//! licence notices WordNet and 12dicts require are in `THIRD-PARTY-NOTICES.md`
//! at the repository root.
//!
//! ## How to use it
//!
//! Two rules, and both are the caller's job:
//!
//! 1. **Lemmatise first.** Members are base forms, because an IF parser accepts
//!    the imperative — you type `take lamp`, never `took lamp`. `illuminated`
//!    will not be found; reduce it to `illuminate` before calling. Skipping this
//!    makes a missing morphology step look like a hole in the data.
//! 2. **Intersect with THIS story's dictionary.** The table proposes; the story
//!    disposes. [`suggest`] takes the predicate and does the rest, including
//!    dropping the word the player typed — it is in its own group by
//!    construction and it is the one word known to have failed.
//!
//! ```ignore
//! let known = |w: &str| grammar.is_verb(w);
//! for word in verb_synonyms::suggest("illuminate", known, 4) {
//!     // "light", if the story knows it
//! }
//! ```
//!
//! Nothing is parsed until the first lookup: most sessions never have a rejected
//! word at all.
//!
//! ## The second table
//!
//! [`irregular_bases`] answers a different question with the same shape: what a
//! word is an inflection OF, when no suffix rule can say. `lit` → `light` and
//! `mice` → `mouse` come from WordNet's own exception lists, generated by the
//! same crate into [`irregular_forms.tsv`] beside the groups. It is what a
//! caller reaches for BEFORE the lemmatise rule above, not instead of it.

#![forbid(unsafe_code)]

use std::collections::HashMap;
use std::sync::OnceLock;

/// The shipped table, as it sits on disk.
///
/// Line order is significant — see [`groups`].
const TABLE: &str = include_str!("synonym_groups.tsv");

/// The parsed table: the groups in file order, and a word's group indices in
/// that same order.
struct Index {
    groups: Vec<Vec<&'static str>>,
    by_word: HashMap<&'static str, Vec<u32>>,
}

fn index() -> &'static Index {
    static INDEX: OnceLock<Index> = OnceLock::new();
    INDEX.get_or_init(|| {
        let mut groups: Vec<Vec<&'static str>> = Vec::new();
        let mut by_word: HashMap<&'static str, Vec<u32>> = HashMap::new();
        for line in TABLE.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let members: Vec<&'static str> = line.split('\t').filter(|w| !w.is_empty()).collect();
            if members.len() < 2 {
                continue;
            }
            let id = groups.len() as u32;
            for w in &members {
                by_word.entry(w).or_default().push(id);
            }
            groups.push(members);
        }
        Index { groups, by_word }
    })
}

/// Every group `word` belongs to, best guess first: the groups games declared
/// for it, then its WordNet senses, commonest sense first.
///
/// The order is the whole reason the file must never be sorted. A word is
/// polysemous: `draw` is *pull*, *sketch* and *attract*, and it sits in one
/// group per sense. Walking them in order and stopping early shows the player
/// the reading they most likely meant, and keeps a rare fifth sense from
/// crowding out the common first one. A group the corpus itself declared comes
/// ahead of all of them, because a game's own verb entry is a stronger
/// statement about what a word does in a parser than any sense ranking.
///
/// `word` must already be a base form; see the module docs.
pub fn groups(word: &str) -> impl Iterator<Item = &'static [&'static str]> {
    let idx = index();
    idx.by_word
        .get(word)
        .map_or(&[][..], Vec::as_slice)
        .iter()
        .map(|&i| idx.groups[i as usize].as_slice())
}

/// What to offer a player whose word the parser rejected: the words in that
/// word's groups that THIS story's dictionary actually contains, most likely
/// sense first, at most `limit` of them.
///
/// `known` is asked about candidate spellings only, so it can be as expensive as
/// a dictionary lookup. The player's own word is never returned: it is in its
/// own group by construction, and it is the one word known to have failed.
///
/// `word` must already be a base form; see the module docs.
pub fn suggest(word: &str, known: impl Fn(&str) -> bool, limit: usize) -> Vec<&'static str> {
    let mut out: Vec<&'static str> = Vec::new();
    for group in groups(word) {
        for &candidate in group {
            if out.len() >= limit {
                return out;
            }
            if candidate != word && !out.contains(&candidate) && known(candidate) {
                out.push(candidate);
            }
        }
    }
    out
}

/// Every single word the table holds, in no particular order — the table read
/// as a plain English lexicon rather than as groups.
///
/// For a caller that needs to know how a word is SPELLED rather than what it
/// means: a Version 3 story stores `activa`, prints `activate` nowhere, and
/// this is where the whole word can still be found (SQ-1553). Phrasal members
/// (`put on`) are left out; they are not one word.
pub fn words() -> impl Iterator<Item = &'static str> {
    index().by_word.keys().copied().filter(|w| !w.contains(' '))
}

/// How many groups the shipped table holds. For diagnostics and for tests that
/// want to know the data is really there.
pub fn group_count() -> usize {
    index().groups.len()
}

// ── Irregular inflections ────────────────────────────────────────────────────

/// The second shipped table: [`irregular_forms.tsv`], beside this file.
///
/// Line order is NOT significant here — see the file's own header.
const IRREGULARS: &str = include_str!("irregular_forms.tsv");

/// An inflected form → every base WordNet resolves it to.
fn irregulars() -> &'static HashMap<&'static str, Vec<&'static str>> {
    static INDEX: OnceLock<HashMap<&'static str, Vec<&'static str>>> = OnceLock::new();
    INDEX.get_or_init(|| {
        let mut by_form: HashMap<&'static str, Vec<&'static str>> = HashMap::new();
        for line in IRREGULARS.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let mut f = line.split('\t');
            let (Some(form), Some(base)) = (f.next(), f.next()) else { continue };
            if form.is_empty() || base.is_empty() {
                continue;
            }
            by_form.entry(form).or_default().push(base);
        }
        by_form
    })
}

/// What `form` might be an irregular inflection OF: `lit` → `light`, `took` →
/// `take`, `went` → `go`, `mice` → `mouse`.
///
/// This is the half of English morphology no suffix rule can reach. A caller
/// that strips endings — `app`'s `vocab::stems` is the one — covers `lighting`
/// and `carries` and cannot ever cover these, because an irregular form shares
/// no letters with the rule that would have made it. A player who types `lit
/// lamp` is not making a typo either, so the near-miss route cannot help: `lit`
/// is two keystrokes from `light` and that threshold is set at one on purpose.
///
/// A SLICE of bases, not one, because a spelling can inflect two ways: `axes` is
/// `ax` and `axis`, `singing` is `sing` and `singe`. Neither reading outranks
/// the other in general, so both are handed back and the caller's own dictionary
/// settles it — which is the same division of labour [`suggest`] uses.
///
/// Verbs and nouns both. An empty slice for anything the table does not hold,
/// which is every regular word in English.
pub fn irregular_bases(form: &str) -> &'static [&'static str] {
    irregulars().get(form).map_or(&[][..], Vec::as_slice)
}

/// How many inflected forms the irregular table holds. For diagnostics, and for
/// a test that wants a missing or truncated file to fail loudly rather than
/// leave the lookup a silent no-op.
pub fn irregular_count() -> usize {
    irregulars().len()
}

#[cfg(test)]
mod tests;
